name: Build and run tests

on:
  push:
  pull_request:
    branches-ignore:
      - gh-pages

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: "Install dependencies"
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build

      - name: "Configure build"
        working-directory: ${{ github.workspace }}
        run: |
          cmake -S . -B build -G Ninja \
            -D CMAKE_BUILD_TYPE=Release \
            -D TACHYON_TOOLS_ENABLE_FORMATTING=OFF \
            -D TACHYON_TOOLS_ENABLE_TAGS=OFF

      - name: "Build"
        working-directory: ${{ github.workspace }}/build
        run: cmake --build .

      - name: "Run tests"
        working-directory: ${{ github.workspace }}/build
        run: ctest
